name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        style: [all, default]
        rust:
          - stable
        include:
          - style: all
            flags: '--all-features'
          - style: default
            flags: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose

  test:
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        style: [all, default]
        rust:
          - stable
        include:
          - style: all
            flags: '--all-features'
          - style: default
            flags: ''
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --verbose